name: Deployment workflow
run-name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - automate-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inject RSA private key to enable SSH connection with deployment server
      run: |
        echo "${{ secrets.RSA_DEPLOY_PRIV_BASE64_ENC }}" | base64 --decode > ./id_rsa

    - name: Prepare RSA private key
      run: |
        sudo mkdir -p ~/.ssh
        sudo mv ./id_rsa ~/.ssh/id_rsa
        sudo chmod 400 ~/.ssh/id_rsa

    - name: Run Ansible playbook
      run: ansible-playbook -i "${{ secrets.DEPLOY_SERVER }}," ./devops/ansible/playbooks/hello-world.yaml
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
