name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your desired steps here
      - name: Step 1
        run: echo "Step 1 executed"

      - name: Step 2
        run: echo "Step 2 executed"
